### ISSUE TITLE
Can't create VM due to network problem

### ISSUE THREAD

**Issue by connortran216** [tranductrinh/k8s#1]
Hi anh, em thử tạo VM bằng Vagrant thì gặp lỗi như sau

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "vboxnet7", "--ip", "172.16.16.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```

**Comment by tranductrinh** [comment]
Hi em, có khả năng đây là vấn đề của Virtuabox: https://stackoverflow.com/questions/69728426/e-accessdenied-when-creating-a-host-only-interface-on-virtualbox-via-vagrant

Phiên bản Virtualbox a dùng là: Version 6.1.26 r145957 (Qt5.6.3) trên macOS

**Comment by tranductrinh** [comment]
Nếu em vẫn chưa fix đc thì feel free để open

**Comment by connortran216** [comment]
> Nếu em vẫn chưa fix đc thì feel free để open

Thanks anh em đã fix được, này có vẻ như là lỗi của VM, em downgrade version xuống thì dùng được bình thường rồi ạ.
